"""removed user

Revision ID: 09823230a859
Revises: dc74e7d79e53
Create Date: 2020-04-14 17:55:12.006665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09823230a859'
down_revision = 'dc74e7d79e53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachment', sa.Column('update_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attachment', 'update_date')
    # ### end Alembic commands ###
