"""remove product vendor relationship

Revision ID: 4cdf868883c9
Revises: e4fad20bc985
Create Date: 2020-05-27 21:18:26.987200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cdf868883c9'
down_revision = 'e4fad20bc985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'product', 'vendor', ['vendor_id'], ['id'])
    # ### end Alembic commands ###
