"""attachment notes tables

Revision ID: 62a98497d8ad
Revises: f40a95457ff1
Create Date: 2020-04-04 15:04:40.925268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62a98497d8ad'
down_revision = 'f40a95457ff1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachment',
    sa.Column('attachment_id', sa.Integer(), nullable=False),
    sa.Column('attachment_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('link', sa.String(length=1000), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('attachment_id', 'attachment_type_id')
    )
    op.create_table('notes',
    sa.Column('notes_id', sa.Integer(), nullable=False),
    sa.Column('notes_type_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('notes_id', 'notes_type_id')
    )
    op.drop_table('product_attachment')
    op.drop_table('product_note')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_note',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=True),
    sa.Column('note', sa.VARCHAR(length=2000), nullable=True),
    sa.Column('create_date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_attachment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('description', sa.VARCHAR(length=2000), nullable=True),
    sa.Column('link', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('create_date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('notes')
    op.drop_table('attachment')
    # ### end Alembic commands ###
