"""add date columns

Revision ID: ac91e2ab4c61
Revises: c985cdc93a58
Create Date: 2020-03-26 17:47:12.122490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac91e2ab4c61'
down_revision = 'c985cdc93a58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('software', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('software', sa.Column('last_update_date', sa.DateTime(), nullable=True))
    op.add_column('software_attachment', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('software_note', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('last_login_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_login_date')
    op.drop_column('software_note', 'create_date')
    op.drop_column('software_attachment', 'create_date')
    op.drop_column('software', 'last_update_date')
    op.drop_column('software', 'create_date')
    # ### end Alembic commands ###
