"""updated notes date

Revision ID: dc74e7d79e53
Revises: a1cc1a75cd6e
Create Date: 2020-04-06 19:41:56.888242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc74e7d79e53'
down_revision = 'a1cc1a75cd6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('update_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'update_date')
    # ### end Alembic commands ###
