"""software table

Revision ID: ee484988dfb9
Revises: 6fe619baa70e
Create Date: 2020-03-23 23:15:59.514910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee484988dfb9'
down_revision = '6fe619baa70e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('software',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('software_name', sa.String(length=80), nullable=True),
    sa.Column('provider', sa.String(length=80), nullable=True),
    sa.Column('department', sa.String(length=80), nullable=True),
    sa.Column('budget_owner', sa.String(length=80), nullable=True),
    sa.Column('software_owner', sa.String(length=80), nullable=True),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.Column('payment_method', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('software')
    # ### end Alembic commands ###
